### ISSUE TITLE
Add keybinding to get context

### ISSUE THREAD

**Issue by EstebanDalelR** [watermelontools/wm-extension#140]
https://code.visualstudio.com/api/references/contribution-points#contributes.keybindings

**Comment by jcbages** [comment]
Hi @EstebanDalelR, I'm interested in taking this Issue but was wondering which keybinding should we associate?

**Comment by EstebanDalelR** [comment]
Hey @jcbages!
Thanks for the interest!
What about CTRL/COMMAND+SHIFT+C for context and CTRL/COMMAND+SHIFT+H for History. I tested and nothing happened so they are free.

**Comment by EstebanDalelR** [comment]
Also, for now, can we bind them if there's selection only?
That makes sense in my head, I select some lines and run it from the keyboard

**Comment by jcbages** [comment]
Hi @EstebanDalelR, here's a PR for solving this issue: https://github.com/watermelontools/wm-extension/pull/295
Let me know if you'd like me to change anything

**Comment by EstebanDalelR** [comment]
Fixed as of https://github.com/watermelontools/wm-extension/pull/295
