### ISSUE TITLE
Fix "Error: Could not register service workers " when loading the extension 

### ISSUE THREAD

**Issue by mduquem1** [watermelontools/wm-extension#167]
This issue tracks this bug which [per this slack thread ](https://watermelonusers.slack.com/archives/C03701VV2FL/p1651246241478359?thread_ts=1651246197.575049&cid=C03701VV2FL)is not consistently reproducible.

`Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..`

![Screen Shot 2022-04-29 at 10 27 56](https://user-images.githubusercontent.com/83253644/165977484-65b05821-e128-403c-b799-f92bdfc91968.png)

# Steps to reproduce

1. Open VS Code
2. Install the WM tools extension
3. Open WM tab 
4. Error described displays on screen

# Ideal situation

We would like to open the WM tab and get the report correctly without errors.

**Comment by EstebanDalelR** [comment]
Closing as this seems to be happening when the user has several instances of Code.
https://stackoverflow.com/questions/67698176/error-loading-webview-error-could-not-register-service-workers-typeerror-fai
