### ISSUE TITLE
Add instructions for running the extension from source code

### ISSUE THREAD

**Issue by jcbages** [watermelontools/wm-extension#294]
Hi! I'm trying to work on an issue but noticed there're no documented instructions regarding how to test my changes in VSCode. I think it'd be helpful to add something like that either in the `README.md` or the `CONTRIBUTING.md`.

**Comment by EstebanDalelR** [comment]
Will do so!
Thanks for the feedback.

**Comment by EstebanDalelR** [comment]
Hey @jcbages 
I updated a little the `[Contributing](https://github.com/watermelontools/wm-extension/blob/dev/CONTRIBUTING.md#running-the-extension)` file, but IDK if it's enough, some feedback would be greatly appreciated!
