### ISSUE TITLE
Organization repositories

### ISSUE THREAD

**Issue by lopezjurip** [watermelontools/wm-extension#317]
I just installed the VSCode extension and I was able to successfully login, but when I try to fetch git history info from my private organization repositories it is failing

<img width="343" alt="Screen Shot 2022-06-23 at 11 42 27" src="https://user-images.githubusercontent.com/7570744/175339734-7b48ceb6-5464-442c-a9aa-28289b6ccbdd.png">

**Comment by EstebanDalelR** [comment]
@lopezjurip Does this continue happening?

**Comment by EstebanDalelR** [comment]
@lopezjurip ?
